### ISSUE TITLE
Separation of polyfills

### ISSUE THREAD

**Issue by wroughtec** [jshjohnson/Choices#117]
I appreciate this is something I can (and will) resolve for my project situation, but thought I would bring it up here anyway as a potential enhancement:

I use a polyfill service:
https://polyfill.io/v2/docs/examples#feature-detection

That I capture all the polyfills we require for our js and progressively enhance so the latest browser Chrome or Firefox do not download extra things they do not require but the older browsers will get the polyfills they do require. Obviously this does mean I try and avoid adding extra polyfills in my main js file to try and save a few bytes (every byte counts)

So potentially it would be nice to separate the polyfills out of the build process and either have 2 versions 1 with and 1 without or have it as a dependancy for older browsers that require .find & .from. Both of which ironically I had to deal with the other day for IE to get our app working ;)

The added advantage being as usage drops out of the older browsers less and less will require these polyfills (one less headache for everyone) and giving the responsibility to the dev to handle their browser support and use a proper strategy when it comes with dealing with the old which in turn will (hopefully) make them a better dev.

Anyway not really a Must in the MOSCOW scale more a of a Could but I thought I would throw it out there.

**Comment by synapticism** [comment]
Since people are already accustomed to having the polyfill included it probably makes sense to keep it there... but shipping a version without the included polyfill would be excellent for those of us who are counting bytes and managing polyfills in some other fashion ;)

BTW for the time being I found Webpack's [null-loader](https://github.com/webpack-contrib/null-loader) useful to safely excise the polyfill bundle from the ES6 source. Test for the absolute path to the polyfill bundle and it'll be knocked out of your build.

**Comment by jshjohnson** [comment]
I'm thinking I should probably build two versions per release; one transpiled to ES5 with polyfills and one in plain ES6 without polyfills.

**Comment by jshjohnson** [comment]
Continuing this conversation [here](https://github.com/jshjohnson/Choices/issues/144)!
