### ISSUE TITLE
Searching using ajax can be really slow

### ISSUE THREAD

**Issue by Remcoman** [jshjohnson/Choices#173]
I've discovered a performance issue when the ajax method returns lots of results and you call it repeatedly. This is caused by the loop at [line 1232 of choices.js](https://github.com/jshjohnson/Choices/blob/master/assets/scripts/src/choices.js#L1232).

For example when the ajax method returns 100 results and is called 2 times, the render method is called 200 times! I fixed this issue by implementing a simple async render method using requestanimationframe. This works fine for my use case but it might break backwards compatibility when the user queries the dom right after calling a method on the choices instance.

@jshjohnson Are you interested in a pr?

**Comment by jshjohnson** [comment]
Sure! Would be interested in seeing how this would work :)

**Comment by Vercjames** [comment]
Any chance on getting this issue resolved? Remcoman do you have a fiddle showcasing your fix?

**Comment by C-Lodder** [comment]
Have you tried increasing the `searchFloor` to something like `3`. Performaing an ajax search after type 1 character may be slow if there are lots of results

**Comment by Vercjames** [comment]
I made a fork showcasing the lockup I'm experiencing when calling large JSON objects.
-- https://github.com/vercjames/choices

I'm fetching car models based on their make. The only thing I altered from the jshjohnson's master branch was the index.html where I replaced the API and removed the components I'm not using.

There are 2 API's so please toggle between the 2 to experience the issue yourself. One is Toyota where I pull in 53 records and takes about 1 maybe 2 seconds to load. The other is Honda where I pull in 788 records and it freezes the browser for about 20 seconds. (You know the browser is locked because you cant click any of the other dropdown's)

I tried your change as well Remcoman and recompiled the the dist directory (choices.min.js) and didnt see a difference. Am I missing something?
