### ISSUE TITLE
How to change value of existing Choice?

### ISSUE THREAD

**Issue by morphikus** [jshjohnson/Choices#277]
I have the existing element select#selector

I can't change developer's src bundle. 
I just need add my fuctionality.

I'd like to do

var selector = new Choices(document.getElementById('selector'));
selector.setValue('bla-bla');

but it doesn't work.

Can you help me?

**Comment by jshjohnson** [comment]
Hey! [setValueByChoice](setValueByChoice) is what you’re after! :)

**Comment by morphikus** [comment]
When I call  setValueByChoice I see "Attempting to select choice that does not exist" in console log.

I need not create a Choice combobox =) I want use the existing Choice combobox.

**Comment by jshjohnson** [comment]
What are you passing as the argument to `setValueByChoice`? You need to pass the value of the option you want to select.

**Comment by morphikus** [comment]
For example:
`<select id="select">
<option value="123">One two three<option>
<option value="456">Four Five Six<option>
</select>
`

Somebody had done the Choice element from select#select earlier.

I'm trying to "connect" to his Choice element
`
var selector = new Choices(document.getElementById('selector'));
selector.setValueByChoice('456');
`
but I see "Attempting to select choice that does not exist" in console log. =))

**Comment by jshjohnson** [comment]
Could you do me a favour and send me the output of `console.log(selector.presetChoices)` please?

Thanks

**Comment by morphikus** [comment]
![image](https://user-images.githubusercontent.com/1226940/31718672-71e0b078-b419-11e7-9811-86e76b664561.png)
 =(

**Comment by jshjohnson** [comment]
Hmm something's not right with your setup. Could you send me your full choices config as well as the markup for the select please?

**Comment by morphikus** [comment]
`if (document.querySelector('.js-choice')) {
  Array.from(document.querySelectorAll('.js-choice')).forEach(
    element => new Choices(element, {
      search: false,
      itemSelectText: '',
      shouldSort: false
    }));
}`

So it's every select at site will become Choice element. I can't change config. I need to work with the existing elements. =(

**Comment by jshjohnson** [comment]
So are you trying to set the value on every single select box? I'm confused

**Comment by sergonius** [comment]
I have a similar issue. I am making every `select` on the page into a Choices instance so I don't really have access to the specific one I want to set the value of.

Choices in my case is inside a wrapper:

```javascript
const Select = (selector = 'select:not(.js-manual-select)', settings = {}) => {
	if (!document.querySelector(selector)) {
		return console.warn('Select: no matching element');
	}

	return new Choices(selector, merge(defaultSettings, settings));
};
```

Since I have access to code, I excluded a certain class as seen above and created an instance separately.
This did give me an error in the console saying `Incompatible input passed`, which seemingly doesn't really affect anything, everything works. (Care to still comment this, though?)

Listening to `select` changes and setting the new value as the Choices instance value of the select would solve @morphikus and my issue I guess. A possibility to retrieve the instance via an HTML element etc would work as well.

**Comment by bennybee** [comment]
I have the same issue, I'm creating many instances of Choices on page init. I don't have access to each choices instance as a variable to update later so would like to target via the source DOM element e.g.

`var elChoice = document.querySelector('.choices-instance');
var choicesInstance = Choices(elChoice);
choicesInstance.setValue(['Set value 1', 'Set value 2'])
`

**Comment by jshjohnson** [comment]
This is fixed in `develop` - soon to be released. Just writing some e2e tests...

**Comment by binarious** [comment]
@jshjohnson Any ETA? Having this issue with 4.1.0.

**Comment by carlwood** [comment]
@jshjohnson Having the same issue.

**Comment by besciualex** [comment]
`<!-- Let's assume we have a select like this: -->`
`<select name="test" id="test">`
`	<option value="1">One</option>`
`	<option value="2">Two</option>`
`</select>`



`//convert all selects on the page in Choices`
`document.getElementsByTagName('select').forEach(function(current_node, index){`	
`	// create a new property on it, which will store Choices `
`	current_node.choices = new Choices(node);`	
`})`


`// Access it anytime using the property declared earlier`
`document.getElementById('test').choices.setValue([{value: 2, label: "Two"}])`

**Comment by abdoMGH** [comment]
i'm gonna switch to another select  :(

**Comment by dezertdezine** [comment]
> i'm gonna switch to another select :(

which one?

**Comment by nikolaosinlight** [comment]
To set the value programatically the following works for me with version v9.0.1
`choices.setChoiceByValue(value);`

Where value is a string for single-select (and apparently can be a an array of multiple values for multiple-select though have not tested).

One weird gotcha - to set the choices to be readonly I had to invoke disable() method however for some reason that does not even send a form value for the choice as part of form post. I get that disable() is not the best method but barring what appears to be no automatic support for readonly what I do is flip to a regular text input box if readonly so server gets a value.  While this is not related to this question it is a gotcha that I hope can help someone else save many hours....

--Nikolaos

**Comment by nikolaosinlight** [comment]
@besciualex 

Not sure if your intention was that setValue() sets the choices to multiple values programatically OR that it adds these additional options b/c it does the latter and perhaps why a comment says it does not work... the correct method to set the value programatically is instead setChoiceByValue().

> document.getElementById('test').choices.setValue([{value: 2, label: "Two"}])

If I misread your intent then apologies but just wanted to point this out to be clear.

**Comment by odysahe** [comment]
How about [this](url) ?

**Comment by kratos-digital** [comment]
If anyone using WPForms, which uses this plugin.

This is how to preselect using JS (after hours of wasted time) and useless ChatGPT responses:

1. WPForms main JS file has line of code that saves Choices instance for each select as jQuery `choicesjs` data
2. Get native select element `const selectEl = document.getElementById(`wpforms-${formId}-field_${selectId}`)`
3. Get instance `const selector = jQuery(selectEl).data("choicesjs");`, you must use jQuery here since data() saves it in some internal jQuery cache (I don't use jQuery so if that's wrong statement, my bad). If you are using jQuery, and not plain JS, as I do, then you can use $ instead
4. Set value `selector.setChoiceByValue(value);` - value must be string, so if you use IDs as value, be sure to convert it to string before passing to setChoiceByValue

Note: I have no idea why the author of the plugin removes options from native select and doesn't allow selecting the value using plain JS and selectEl.value with change event.
