### ISSUE TITLE
IE11 - Single select

### ISSUE THREAD

**Issue by zslabs** [jshjohnson/Choices#28]
Hi! 
Not necessarily a bug, but a difference in behavior than other browsers - when selecting a single-select in IE11, the dropdown remains open, compared to Chrome, Firefox, and Safari (latest) it's closed on selection. I'll see if I can spot anything unless you come across anything quicker. Thanks!

**Comment by zslabs** [comment]
It looks like IE11 doesn't like `const hasActiveDropdown = this.dropdown.classList.contains(this.config.classNames.activeState);` in `assets/scripts/src/choices.js` => `_onBlur`. Continuing to look.

**Comment by zslabs** [comment]
It appears to be working on the second click to your selection (can be the same or a different one)

**Comment by jshjohnson** [comment]
Thanks for highlighting this - it's a bug. I'll look into this ASAP.

**Comment by jshjohnson** [comment]
If anybody has any ideas on why this is happening I'd be keen to know! It seems to be something to do with the ordering of blur/focus events but I'm not sure

**Comment by jshjohnson** [comment]
As of version 2.0.0 this has now been resolved. The problem was to do with the ordering of focus/blur events. Now if you focus a single select element the dropdown will not open; the dropdown will only open if you press the enter/up/down key or click it. This is the same behaviour as normal select boxes which is even better.

Thanks for the heads up!

**Comment by zslabs** [comment]
Awesome, thanks for looking into this!
