### ISSUE TITLE
Is it possible to use serverside searching?

### ISSUE THREAD

**Issue by martijnvbeek** [jshjohnson/Choices#332]
Can Choices be configured to use serverside searching (type-a-head)? eg. Fetch 5 results from server when 3 characters or more are entered in the search field?

**Comment by fernandoagarcia** [comment]
You need a searchable index. Its cheaper to pull all available choices in one call rather than making a call after every segment of letters.

**Comment by martijnvbeek** [comment]
I'm using an elasticsearch index for the obvious reasons. Can it be done?

**Comment by fernandoagarcia** [comment]
Yeah you can use the instance.ajax() method from the api.

**Comment by martijnvbeek** [comment]
Where can I find an example? The only example I can find is loading data from the server on initialising.

**Comment by martijnvbeek** [comment]
As far as I can determine it's not possible to query the server when the user has typed 3 characters or more are show the results from the server in Choices. The `instance.ajax()` method is only called when the component is initialised.

**Comment by fernandoagarcia** [comment]
There is no method that directly covers your use case. Your solution will require a combination of custom code mixed with the methods provided by the choices api.  To query the server seems like a custom solution Tied in the the instance.search() listener. Then once you get a response you initialized/reinitialize the options or the choices instance. But the main reason why there are no samples is because this is specific to your case. Choices requires a searchable index but if you dont have one until an action is taken then it maybe a difficult approach. Would agree that it would be great for the api to work with elastic search right out of the box.

**Comment by jshjohnson** [comment]
Just seconding what @fernandoagarcia said. Choices is a client-side library so any server logic will need to handled yourself. You could make a debounced request using the [search](https://github.com/jshjohnson/Choices#search) event.

**Comment by martijnvbeek** [comment]
Thanks, with your directions I've constructed a solutions:

`
let element = document.querySelector('#auto-complete');
let uri = 'https://example.org/search';
let choice = new Choices(element, {
    removeItemButton: false,
    itemSelectText: '',
    shouldSort: false,
});
let timer = null;

choice.passedElement.addEventListener('search', function (event) {
    if (event.detail.value.length > 3) {
        
        if (null !== timer) {
            clearTimeout(timer);
        }

        timer = setTimeout(function () {

            let request = new Request(uri + "?term=" + event.detail.value, {
                credentials: 'same-origin',
            });

            fetch(request)
                .then(function (response) {
                    if (200 === response.status) {
                        response.json().then(function (data) {
                            choice.setChoices(data, 'id', 'label', true);
                        });
                    }
                })
                .catch(function (error) {
                    console.log(error);
                })
            ;
        }, 1000);
    }
});
`
