### ISSUE TITLE
removeItemsByValue(value) only work when value is String and choices value is String, but not Number

### ISSUE THREAD

**Issue by tonghia** [jshjohnson/Choices#354]
When I want to remove a selected item I used removeItemsByValue

I see some issues with this function from the source

```
removeItemsByValue(value) {
    if (!value || !isType('String', value)) {
      return this;
    }

    const items = this.store.getItemsFilteredByActive();

    items.forEach((item) => {
      if (item.value === value) {
        this._removeItem(item);
      }
 });

```

The issue is that the value param must always be the String type, but when to init the choice we still can init values with Number type. So, in that case, this function would not work.

Atm, I have to converse all choices value to String then convert it to Number again when I want to use its value. Am I using the wrong function or do we have a better solution for my case?

**Comment by fernandoagarcia** [comment]
@tonghia you can also just convert the int.toString()  so that you can always expect a string. this is a pretty common practice and no need to check if it is a string.

**Comment by tonghia** [comment]
@fernandoagarcia sorry for not write a clear comment. The function I posted is from the source code. I think it is a bug. Do you think so?

**Comment by fernandoagarcia** [comment]
@tonghia your comment was fine. I was just trying to envision what you were trying to achieve. Didn't know if I answered your question correctly.  I ran into the same issue because my values were integers as well so I am familiar with this issue. I think it was a matter of preference because otherwise the API would have to account for all variable types. You can try a pull request to see how you can solve common variable type issues. But I think a string fits most use cases.  I may be wrong but that's what I got from it.
