### ISSUE TITLE
Bundle size increase from 3.0.4 to 4.1.3

### ISSUE THREAD

**Issue by perifer** [jshjohnson/Choices#480]
Is a bundle size increase from 19kb (zipped https://github.com/jshjohnson/Choices/blob/v3.0.4/assets/scripts/dist/choices.min.js) to 26.2KB (zipped, https://github.com/jshjohnson/Choices/blob/v4.1.3/public/assets/scripts/choices.min.js) (around 37%) to be expected? 

It's still a very small package - one of the reason why I use and love it. But maybe it indicates something that could be configured e.g with my webpack setup, release notes for 4.0.0 for example mentions "more modular code"?

**Comment by jshjohnson** [comment]
Unfortunately this is one of those trade offs. In earlier versions of Choices, nearly all the code was in monolithic class which was horrendous to maintain (it arguably still is). In an attempt to improve this I began extracting functionality but this in turn increases bundle size. 

Upgrading webpack is something worth trying regardless but yeah, that's why!

**Comment by jshjohnson** [comment]
I've made a few changes to reduce the bundlesize back to 22kb. I've also added some CI checks to ensure the JS bundle doesn't exceed 25kb 👍
